parameters:
    main.example.class: Application\Niagara\MainBundle\Example

services:
#    main.example:
#        class: %main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    niagara_main.menu_builder:
        class: Application\Niagara\MainBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", "@doctrine.orm.entity_manager"]
    niagara_main.menu.main:
        class: Knp\Menu\MenuItem
        factory_service: niagara_main.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request
        tags:
            - {name: knp_menu.menu, alias: main}
